name = "meinPaket"
uuid = "82d05d4c-0a19-4a69-b15f-7ebbef44f2b9"
authors = ["Nicklas Hafiz"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
